// Review Action Types

export const REVIEW_DETAILS_SUCCESS = "REVIEW_DETAILS_SUCCESS";
export const REVIEW_DETAILS_FAIL = "REVIEW_DETAILS_FAIL";
export const REVIEW_CREATION_SUCCESS = "REVIEW_CREATION_SUCCESS";
export const REVIEW_CREATION_FAIL = "REVIEW_CREATION_FAIL";