// Review Action Types

// Create 
export const REVIEW_CREATION_SUCCESS = "REVIEW_CREATION_SUCCESS";
export const REVIEW_CREATION_FAIL = "REVIEW_CREATION_FAIL";

// Delete
export const REVIEW_DELETION_SUCCESS = "REVIEW_DELETION_SUCCESS";
export const REVIEW_DELETION_FAIL = "REVIEW_DELETION_FAIL";

// Update
export const REVIEW_UPDATE_SUCCESS = "REVIEW_UPDATE_SUCCESS";
export const REVIEW_UPDATE_FAIL = "REVIEW_UPDATE_FAIL";
