// Review Action Types

export const REVIEW_CREATION_SUCCESS = "REVIEW_CREATION_SUCCESS";
export const REVIEW_CREATION_FAIL = "REVIEW_CREATION_FAIL";

export const REVIEW_DELETION_SUCCESS = "REVIEW_DELETION_SUCCESS";
export const REVIEW_DELETION_FAIL = "REVIEW_DELETION_FAIL";
